admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001

node:
  cluster: test-cluster
  id: test-id

dynamic_resources:
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: control_plane # can be overridden with "--xds-cluster"
  cds_config:
    ads: {}
    resource_api_version: V3
  lds_config:
    ads: {}
    resource_api_version: V3

static_resources:
  clusters:
    - name: control_plane
      type: strict_dns
      connect_timeout: 1s
      http2_protocol_options: {}
      load_assignment:
        cluster_name: control_plane
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: host.docker.internal
                    port_value: 18000 # can be overridden with "--xds-port"