apiVersion: 1

# List of data sources to insert/update depending on what is available in the database.
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    isDefault: